name: Check Python code format

# yamllint disable-line rule:truthy
on: [push]

jobs:
  linter_name:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v3
